[project]
name = "rss-qualiopi"
version = "0.1.0"
description = ""
authors = [
    {name = "PhiC Perso",email = "phic13@orange.fr"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "rss_qualiopi", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)"
]
