name: Generate RSS Feeds

on:
  schedule:
    - cron: "0 * * * *"   # exécution toutes les heures
  workflow_dispatch:       # déclenchement manuel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install feedparser

      - name: Generate RSS feeds
        working-directory: docs
        run: |
          python aggregate.py

      - name: Commit and push generated XML
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/*.xml
          git commit -m "Update RSS feeds" || echo "No changes"
          git push
